source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Calendouer' do
    pod 'Kingfisher'
    pod 'SnapKit'
    pod 'lottie-ios'
    pod 'SwipeableTabBarController'
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'TKSwitcherCollection'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "YES"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end

