source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Calendouer' do
    pod 'SDWebImage', '~> 3.8'
    pod 'SnapKit', '~> 3.0.2'
    pod 'lottie-ios', '~> 1.0.4'
    pod 'SwipeableTabBarController', '~> 1.0.0'
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'Alamofire', '~> 4.4'
    pod 'TKSwitcherCollection'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "YES"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end

